os: osx
language: Swift
osx_image: xcode10.1
script:
  - xctool -workspace watcher.xcworkspace -scheme watcher -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace watcher.xcworkspace -scheme watcher -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
